language: php

matrix:
  include:
    - php: 5.3
      dist: precise

sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer install --no-interaction

script:
- vendor/bin/phpunit